spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: finance_user
    password: finance_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

logging:
  file:
    name: finance.log
